
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jul 27, 2017 03:58:46 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
    from tkinter.filedialog import askopenfilename

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import encrypt

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    encrypt.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    encrypt.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.var =StringVar()
        self.var2 =StringVar()
        top.geometry("600x450+630+130")
        top.title("New Toplevel 1")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.1, rely=0.11, relheight=0.68, relwidth=0.81)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=485)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.19, rely=0.49, height=18, width=71)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Output File''')

        self.Browse = Button(self.Frame1,command =encrypt.callback)
        self.Browse.place(relx=0.45, rely=0.3, height=26, width=67)
        self.Browse.configure(activebackground="#d9d9d9")
        self.Browse.configure(text='''Browse''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.21, rely=0.3, height=18, width=66)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''File Name''')

        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.39, rely=0.82, relheight=0.07, relwidth=0.3)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(show="*")

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.23, rely=0.82, height=18, width=60)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Password''')

        self.Entry1 = Entry(self.Frame1)
        self.Entry1.place(relx=0.39, rely=0.49, relheight=0.07, relwidth=0.3)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")

        self.Radiobutton1 = Radiobutton(self.Frame1, text="encrypt", variable=self.var, value="en")
        self.Radiobutton1.place(relx=0.39, rely=0.59, relheight=0.07
                , relwidth=0.13)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''encrypt''')

        self.Radiobutton2 = Radiobutton(self.Frame1, text="decrypt", variable=self.var, value="d")
        self.Radiobutton2.place(relx=0.39, rely=0.69, relheight=0.07
                , relwidth=0.13)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''decrypt''')

        self.Entry3 = Label(self.Frame1,textvariable=self.var2)
        self.Entry3.place(relx=0, rely=0.4, relheight=0.07, relwidth=1)
        # self.Entry3.configure(background="white")
        # self.Entry3.configure(text='''''')
        self.Entry3.configure(activebackground="#c4c4c4")

        self.Message1 = Message(self.Frame1)
        self.Message1.place(relx=0.35, rely=0.1, relheight=0.11, relwidth=0.31)
        self.Message1.configure(text='''Enter Parameters''')
        self.Message1.configure(width=150)

        self.Done = Button(top,command=encrypt.encrypt_decrypt_dummy)
        self.Done.place(relx=0.8, rely=0.82, height=26, width=67)
        self.Done.configure(activebackground="#d9d9d9")
        self.Done.configure(text='''Done''')

        self.Message2 = Message(top)
        self.Message2.place(relx=0.08, rely=0.82, relheight=0.04, relwidth=0.46)
        self.Message2.configure(text='''Credit: https://github.com/markpsycho''')
        self.Message2.configure(width=273)






if __name__ == '__main__':
    vp_start_gui()



